{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Data from Factory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=`jwt-pizza-service`, type=\"factory\"} | json | logfmt | drop __error__, __error_details__"
    }
   ]
  },
  {
   "title": "DB queries Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\", type=\"DB\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\"} | json | method != \"\" | logfmt | drop __error__, __error_details__"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Reqs/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_all{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "ALL"
    },
    {
     "expr": "rate(request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Cpu&Memory Metrics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osMetrics_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "osMetrics_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Pizza&Revenue/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    },
    {
     "expr": "rate(pizza_number_sold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "# of Pizza Sold"
    }
   ]
  },
  {
   "title": "Authentication Success/Fail per min Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(auth_failed{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(auth_successful{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}